import type {GadgetDefinition,GadgetType,PhysicalProperties} from "./types.ts";

const base:PhysicalProperties={shape:"rectangle",width:50,height:50,massKg:5,density:.001,friction:.4,staticFriction:.5,airFriction:.01,restitution:.1,gravityScale:1,isStatic:false,isSensor:false,waterReaction:"collide",fireReaction:"none",impactReaction:"none"};
const physics=(overrides:Partial<PhysicalProperties>):PhysicalProperties=>({...base,...overrides});
const canvas=(renderer:string)=>({idle:{kind:"canvas" as const,renderer,loop:true}});
const fixed=physics({isStatic:true,gravityScale:0,massKg:1000,density:.01});

export const GADGET_CATALOG:Record<GadgetType,GadgetDefinition>={
  ball:{type:"ball",displayName:"Bowlingkugel",icon:"●",description:"Schwere Kugel; erzeugt durch Fallhöhe einen großen Impuls.",categories:["dynamic"],tags:["ball","falling-body","rope-end","rolling"],physics:physics({shape:"circle",radius:18,massKg:7.2,density:.006,friction:.12,staticFriction:.18,restitution:.35,impactReaction:"roll"}),appearance:{renderer:"bowling-ball",color:"#293c45"},defaultState:"idle",animations:canvas("bowling-ball"),rotatable:false,removable:true},
  tennisBall:{type:"tennisBall",displayName:"Tennisball",icon:"●",description:"Leichte, stark federnde Kugel mit kleinerem Impuls.",categories:["dynamic"],tags:["ball","falling-body","rope-end","rolling","lightweight"],physics:physics({shape:"circle",radius:12,massKg:.058,density:.002,friction:.18,staticFriction:.2,restitution:.68,impactReaction:"bounce"}),appearance:{renderer:"tennis-ball",color:"#d7eb4c"},defaultState:"idle",animations:canvas("tennis-ball"),rotatable:false,removable:true},
  ramp:{type:"ramp",displayName:"Holzplanke",icon:"╱",description:"Feste Fläche, die rollende und gleitende Körper umlenkt.",categories:["fixed","surface"],tags:["solid-surface","support","wood"],physics:{...fixed,shape:"rectangle",width:155,height:14,friction:.42,staticFriction:.58,waterReaction:"collide",fireReaction:"ignite",impactReaction:"stop"},appearance:{renderer:"wood-ramp",color:"#8d5426"},defaultState:"idle",animations:canvas("wood-ramp"),rotatable:true,removable:true},
  belt:{type:"belt",displayName:"Antriebsriemen",icon:"⛓",description:"Legt sich sichtbar um zwei Antriebsräder und überträgt deren Drehbewegung.",categories:["connector","force-transfer"],tags:["drive-connector","water-ignored"],physics:physics({shape:"none",massKg:0,density:0,gravityScale:0,isStatic:true,isSensor:true,waterReaction:"ignore"}),appearance:{renderer:"drive-belt",color:"#6a4930"},defaultState:"idle",animations:{idle:{kind:"canvas",renderer:"drive-belt",loop:true},running:{kind:"canvas",renderer:"drive-belt-running",frames:12,frameDurationMs:70,loop:true}},rotatable:false,removable:true},
  fan:{type:"fan",displayName:"Ventilator",icon:"✣",description:"Erzeugt einen gerichteten Luftstrom mit begrenzter Reichweite.",categories:["fixed","force-source"],tags:["air-source","solid-shape"],physics:{...fixed,shape:"circle",radius:30,massKg:18,waterReaction:"collide",impactReaction:"stop"},appearance:{renderer:"fan",color:"#18475a"},defaultState:"idle",animations:{idle:{kind:"canvas",renderer:"fan",frames:1,loop:true},running:{kind:"canvas",renderer:"fan-running",frames:6,frameDurationMs:80,loop:true}},rotatable:true,removable:true},
  trampoline:{type:"trampoline",displayName:"Trampolin",icon:"⌁",description:"Spiegelt den Impuls an seiner Flächennormalen nach oben.",categories:["fixed","surface","force-transfer"],tags:["support","bounce-surface","solid-shape"],physics:{...fixed,shape:"rectangle",width:135,height:18,restitution:.9,impactReaction:"bounce"},appearance:{renderer:"trampoline",color:"#c33a2c"},defaultState:"idle",animations:canvas("trampoline"),rotatable:true,removable:true},
  pulley:{type:"pulley",displayName:"Festrolle",icon:"◉",description:"Lenkt Seilzug um; ihre Achse bleibt fest.",categories:["fixed","force-transfer"],tags:["pulley","fixed-pulley","rope-port","solid-shape"],physics:{...fixed,shape:"circle",radius:30,massKg:12},appearance:{renderer:"fixed-pulley",color:"#d39a28"},defaultState:"idle",animations:canvas("fixed-pulley"),rotatable:false,removable:true},
  movingPulley:{type:"movingPulley",displayName:"Lose Rolle",icon:"◎",description:"Bewegt sich mit der Last; mehrere tragende Seilabschnitte teilen die Kraft.",categories:["dynamic","force-transfer"],tags:["pulley","moving-pulley","rope-port","solid-shape"],physics:physics({shape:"circle",radius:30,massKg:8,density:.003,impactReaction:"roll"}),appearance:{renderer:"moving-pulley",color:"#4f9da8"},defaultState:"idle",animations:canvas("moving-pulley"),rotatable:false,removable:true},
  rope:{type:"rope",displayName:"Seil",icon:"∿",description:"Überträgt ausschließlich Zug; ein schlaffes Seil kann nicht drücken.",categories:["connector","force-transfer"],tags:["tension-only","water-ignored"],physics:physics({shape:"none",massKg:.2,density:0,gravityScale:1,isStatic:false,isSensor:true,waterReaction:"ignore"}),appearance:{renderer:"rope",color:"#6b4930"},defaultState:"slack",animations:{slack:{kind:"canvas",renderer:"rope-slack",loop:true},taut:{kind:"canvas",renderer:"rope-taut",loop:true}},rotatable:false,removable:true},
  needle:{type:"needle",displayName:"Nadel",icon:"▲",description:"Starre Spitze; beschädigt ausschließlich ballonartige Hüllen.",categories:["fixed","trigger"],tags:["sharp","solid-shape"],physics:{...fixed,shape:"rectangle",width:16,height:70,massKg:2,impactReaction:"trigger"},appearance:{renderer:"needle",color:"#737c80"},defaultState:"idle",animations:canvas("needle"),rotatable:true,removable:true},
  mouse:{type:"mouse",displayName:"Mogli",icon:"●",description:"Flieht vor einer Katze auf annähernd gleicher Höhe.",categories:["dynamic","animal"],tags:["prey","mouse","water-averse","falling-body"],physics:physics({shape:"circle",radius:22,massKg:.025,density:.001,friction:.5,restitution:.08,inertiaLocked:true,waterReaction:"flee"}),appearance:{renderer:"sprite"},defaultState:"waiting",animations:{waiting:{kind:"sprite",asset:"/assets/mouse-running-sprites.png",row:0,frames:1,columns:3,frameDurationMs:260,width:60,height:60,loop:true},running:{kind:"sprite",asset:"/assets/mouse-running-sprites.png",row:0,frames:3,columns:3,frameDurationMs:110,width:60,height:60,loop:true},falling:{kind:"sprite",asset:"/assets/mouse-running-sprites.png",row:0,frames:3,columns:3,frameDurationMs:90,width:60,height:60,loop:true}},rotatable:false,removable:true},
  gear:{type:"gear",displayName:"Zahnrad",icon:"⚙",description:"Überträgt Drehung auf ein berührendes Zahnrad in Gegenrichtung.",categories:["fixed","force-transfer"],tags:["gear","rotational-port","solid-shape"],physics:{...fixed,shape:"circle",radius:42,massKg:10},appearance:{renderer:"gear",color:"#d39a28"},defaultState:"idle",animations:{idle:{kind:"canvas",renderer:"gear",loop:true},running:{kind:"canvas",renderer:"gear-running",frames:12,frameDurationMs:45,loop:true}},rotatable:false,removable:true},
  cannon:{type:"cannon",displayName:"Kanone",icon:"◒",description:"Feuert nach vollständigem Abbrand ihrer Lunte eine leichte Kanonenkugel.",categories:["fixed","trigger"],tags:["cannon","fuse-target","solid-shape"],physics:{...fixed,shape:"rectangle",width:90,height:44,massKg:220,fireReaction:"explode",impactReaction:"stop"},appearance:{renderer:"cannon",color:"#263d43"},defaultState:"idle",animations:{idle:{kind:"canvas",renderer:"cannon",loop:true},fuseBurning:{kind:"sprite",asset:"/assets/fire-animation-sprites.png",row:1,frames:6,columns:6,frameDurationMs:80,width:34,height:34,loop:true},firing:{kind:"sprite",asset:"/assets/fire-animation-sprites.png",row:2,frames:6,columns:6,frameDurationMs:87,width:105,height:78,loop:false}},rotatable:true,removable:true},
  fuse:{type:"fuse",displayName:"Luntenstück",icon:"⌁",description:"Brennt räumlich von jeder berührten Feuerstelle in beide Richtungen.",categories:["fixed","fire","connector"],tags:["fuse","flammable","extinguishable"],physics:physics({shape:"sensor",width:110,height:8,massKg:.1,density:.0001,gravityScale:0,isStatic:true,isSensor:true,waterReaction:"extinguish",fireReaction:"ignite",impactReaction:"trigger"}),appearance:{renderer:"fuse",color:"#4f3d2b"},defaultState:"idle",animations:{idle:{kind:"canvas",renderer:"fuse",loop:true},burning:{kind:"sprite",asset:"/assets/fire-animation-sprites.png",row:1,frames:6,columns:6,frameDurationMs:80,width:34,height:34,loop:true},burned:{kind:"canvas",renderer:"fuse-burned",loop:true},extinguished:{kind:"canvas",renderer:"fuse-wet",loop:true}},rotatable:true,removable:true},
  bucket:{type:"bucket",displayName:"Wassereimer",icon:"▱",description:"Offener Behälter, der kippen und kollidierende Wasserpartikel ausschütten kann.",categories:["dynamic","container"],tags:["water-container","solid-shape","hinged"],physics:physics({shape:"compound",width:76,height:64,massKg:4,density:.002,friction:.4,staticFriction:.6,waterReaction:"collect",impactReaction:"transfer"}),appearance:{renderer:"bucket",color:"#4c8da8"},defaultState:"full",animations:{full:{kind:"canvas",renderer:"bucket-full",loop:true},pouring:{kind:"sprite",asset:"/assets/water-animation-sprites.png",row:2,frames:6,columns:6,frameDurationMs:230,width:105,height:78,loop:false},empty:{kind:"canvas",renderer:"bucket-empty",loop:true}},rotatable:true,removable:true},
  seesaw:{type:"seesaw",displayName:"Wippe",icon:"⚖",description:"Überträgt Drehmoment um einen festen Drehpunkt; ein Anschlag begrenzt den Winkel.",categories:["dynamic","force-transfer","surface"],tags:["seesaw","support","hinged","solid-shape"],physics:physics({shape:"rectangle",width:232.5,height:18,massKg:18,density:.0032,friction:.7,staticFriction:.85,restitution:.08,impactReaction:"transfer"}),appearance:{renderer:"seesaw",color:"#ad6a2d"},joint:{kind:"pivot",localX:0,localY:0,stiffness:1,damping:.16},defaultState:"idle",animations:canvas("seesaw"),rotatable:true,removable:true},
  hamsterWheel:{type:"hamsterWheel",displayName:"Louis im Hamsterrad",icon:"◉",description:"Stationärer Antrieb; Louis erzeugt Drehbewegung.",categories:["fixed","force-source"],tags:["rotational-source","belt-port","solid-shape"],physics:{...fixed,shape:"rectangle",width:104,height:104,massKg:25},appearance:{renderer:"sprite"},defaultState:"idle",animations:{idle:{kind:"sprite",asset:"/assets/hamster-wheel-sprites.png",row:0,frames:1,columns:3,frameDurationMs:400,width:116,height:116,loop:true},running:{kind:"sprite",asset:"/assets/hamster-wheel-sprites.png",row:0,frames:6,columns:3,frameDurationMs:90,width:116,height:116,loop:true}},rotatable:false,removable:false},
  conveyor:{type:"conveyor",displayName:"Laufband",icon:"▰",description:"Zwei sichtbare Räder führen das Band; ein angeschlossener Antrieb bewegt aufliegende Körper nach links oder rechts.",categories:["fixed","force-transfer","surface"],tags:["conveyor","belt-port","support","solid-shape"],physics:{...fixed,shape:"rectangle",width:270,height:24,massKg:180,friction:.9},appearance:{renderer:"conveyor",color:"#93511f"},defaultState:"idle",animations:{idle:{kind:"canvas",renderer:"conveyor",loop:true},running:{kind:"canvas",renderer:"conveyor-running",frames:8,frameDurationMs:90,loop:true}},rotatable:false,removable:false},
  exit:{type:"exit",displayName:"Ausgang",icon:"→",description:"Sensorischer Zielbereich.",categories:["fixed","target"],tags:["goal-zone"],physics:physics({shape:"sensor",width:55,height:130,massKg:0,density:0,gravityScale:0,isStatic:true,isSensor:true,waterReaction:"ignore",impactReaction:"trigger"}),appearance:{renderer:"exit",color:"#183f49"},defaultState:"idle",animations:canvas("exit"),rotatable:false,removable:false},
  balloon:{type:"balloon",displayName:"Luftballon",icon:"●",description:"Sehr leichter Körper mit stetigem Auftrieb; kann platzen oder angebunden sein.",categories:["dynamic"],tags:["balloon","buoyant","fragile","falling-body"],physics:physics({shape:"circle",radius:24,massKg:.012,density:.00012,friction:.05,airFriction:.025,restitution:.15,gravityScale:1,buoyancyForce:-.00032,waterReaction:"collide",fireReaction:"none",impactReaction:"bounce"}),appearance:{renderer:"balloon",color:"#1976b9"},defaultState:"free",animations:{free:{kind:"canvas",renderer:"balloon",loop:true},tethered:{kind:"canvas",renderer:"balloon-tethered",loop:true},popped:{kind:"canvas",renderer:"balloon-pop",frames:5,frameDurationMs:70,loop:false}},rotatable:false,removable:false},
  candle:{type:"candle",displayName:"Kerze",icon:"♨",description:"Feuerquelle, die je nach Level feststehen oder als physischer Körper fallen kann; Wasser löscht die Flamme.",categories:["fixed","fire","force-source"],tags:["fire-source","extinguishable","solid-shape","falling-body"],physics:physics({shape:"sensor",width:50,height:100,massKg:1,density:.001,gravityScale:0,isStatic:true,isSensor:true,waterReaction:"extinguish",fireReaction:"extinguish-source",impactReaction:"trigger"}),appearance:{renderer:"candle",color:"#f1cb62"},defaultState:"burning",animations:{burning:{kind:"sprite",asset:"/assets/fire-animation-sprites.png",row:0,frames:6,columns:6,frameDurationMs:105,width:82,height:90,loop:true},extinguished:{kind:"canvas",renderer:"candle-smoke",frames:4,frameDurationMs:100,loop:false}},rotatable:false,removable:false},
  targetRing:{type:"targetRing",displayName:"Zielring",icon:"○",description:"Sensorischer Durchflugbereich für Ballons.",categories:["fixed","target"],tags:["goal-zone","balloon-target"],physics:physics({shape:"sensor",radius:45,massKg:0,density:0,gravityScale:0,isStatic:true,isSensor:true,waterReaction:"ignore",impactReaction:"trigger"}),appearance:{renderer:"target-ring",color:"#c73b2e"},defaultState:"idle",animations:canvas("target-ring"),rotatable:false,removable:false},
  basket:{type:"basket",displayName:"Korb",icon:"∪",description:"Fängt Zielkörper und erzeugt ein Levelsignal.",categories:["fixed","target","container"],tags:["goal-zone","catcher"],physics:physics({shape:"sensor",width:100,height:90,massKg:10,density:.001,gravityScale:0,isStatic:true,isSensor:true,waterReaction:"collect",impactReaction:"trigger"}),appearance:{renderer:"basket",color:"#7a421e"},defaultState:"idle",animations:canvas("basket"),rotatable:false,removable:false},
  weight:{type:"weight",displayName:"50-kg-Gewicht",icon:"■",description:"Schwere Last mit Seilanschluss.",categories:["dynamic"],tags:["load","rope-port","falling-body","solid-shape"],physics:physics({shape:"rectangle",width:64,height:64,massKg:50,density:.008,friction:.6,staticFriction:.8,restitution:.02,impactReaction:"stop"}),appearance:{renderer:"weight",color:"#555d60"},defaultState:"idle",animations:canvas("weight"),rotatable:false,removable:false},
  cat:{type:"cat",displayName:"Joanne",icon:"●",description:"Katze mit Ruhe-, Lauf- und Schreckzustand; fällt ohne Untergrund.",categories:["dynamic","animal"],tags:["predator","cat","water-averse","falling-body"],physics:physics({shape:"rectangle",width:60,height:48,massKg:4.2,density:.002,friction:.65,staticFriction:.75,restitution:.04,inertiaLocked:true,waterReaction:"flee",impactReaction:"transfer"}),appearance:{renderer:"sprite"},defaultState:"idle",animations:{idle:{kind:"sprite",asset:"/assets/cat-animation-sprites.png",row:0,frames:3,columns:3,frameDurationMs:420,width:90,height:90,anchorY:-12,loop:true},running:{kind:"sprite",asset:"/assets/cat-animation-sprites.png",row:1,frames:3,columns:3,frameDurationMs:105,width:106,height:106,loop:true},startled:{kind:"sprite",asset:"/assets/cat-animation-sprites.png",row:2,frames:3,columns:3,frameDurationMs:115,width:112,height:112,anchorY:-16,loop:true},falling:{kind:"sprite",asset:"/assets/cat-animation-sprites.png",row:2,frames:3,columns:3,frameDurationMs:115,width:112,height:112,anchorY:-16,loop:true}},rotatable:false,removable:false},
  gearSource:{type:"gearSource",displayName:"Antriebszahnrad",icon:"⚙",description:"Festes Zahnrad als Drehquelle.",categories:["fixed","force-source"],tags:["gear","rotational-source","solid-shape"],physics:{...fixed,shape:"circle",radius:42,massKg:20},appearance:{renderer:"gear",color:"#d39a28"},defaultState:"running",animations:{running:{kind:"canvas",renderer:"gear-running",frames:12,frameDurationMs:45,loop:true}},rotatable:false,removable:false},
  gearTarget:{type:"gearTarget",displayName:"Zielzahnrad",icon:"⚙",description:"Empfängt Drehung und meldet die vollständige Zahnradkette.",categories:["fixed","target","force-transfer"],tags:["gear","rotation-target","solid-shape"],physics:{...fixed,shape:"circle",radius:42,massKg:20},appearance:{renderer:"gear",color:"#bf432d"},defaultState:"idle",animations:{idle:{kind:"canvas",renderer:"gear",loop:true},running:{kind:"canvas",renderer:"gear-running",frames:12,frameDurationMs:45,loop:true}},rotatable:false,removable:false},
  cannonTarget:{type:"cannonTarget",displayName:"Zielscheibe",icon:"◎",description:"Sensorisches Ziel für die Kanonenkugel.",categories:["fixed","target"],tags:["goal-zone","projectile-target"],physics:physics({shape:"sensor",radius:48,massKg:0,density:0,gravityScale:0,isStatic:true,isSensor:true,waterReaction:"ignore",impactReaction:"trigger"}),appearance:{renderer:"cannon-target",color:"#c73b2e"},defaultState:"idle",animations:canvas("cannon-target"),rotatable:false,removable:false},
  steelBeam:{type:"steelBeam",displayName:"Stahlträger",icon:"━",description:"Sehr schwere, nicht brennbare feste Fläche.",categories:["fixed","surface"],tags:["support","solid-shape","metal"],physics:{...fixed,shape:"rectangle",width:235,height:18,massKg:800,friction:.12,staticFriction:.2,fireReaction:"none"},appearance:{renderer:"steel-beam",color:"#6e858d"},defaultState:"idle",animations:canvas("steel-beam"),rotatable:false,removable:false},
  woodWall:{type:"woodWall",displayName:"Holzwand",icon:"▮",description:"Feste, brennbare Wand.",categories:["fixed","surface"],tags:["solid-shape","wood"],physics:{...fixed,shape:"rectangle",width:24,height:180,massKg:300,friction:.32,fireReaction:"ignite"},appearance:{renderer:"wood-wall",color:"#9b5e2a"},defaultState:"idle",animations:canvas("wood-wall"),rotatable:false,removable:false},
  stoneWall:{type:"stoneWall",displayName:"Steinmauer",icon:"▮",description:"Schwere, feuerfeste Wand mit hoher Reibung.",categories:["fixed","surface"],tags:["solid-shape","stone"],physics:{...fixed,shape:"rectangle",width:42,height:170,massKg:1200,friction:.5,staticFriction:.7},appearance:{renderer:"stone-wall",color:"#7d817e"},defaultState:"idle",animations:canvas("stone-wall"),rotatable:false,removable:false},
  payloadBall:{type:"payloadBall",displayName:"Rote Kugel",icon:"●",description:"Leichte Zielkugel für Hebel- und Katapultaufgaben.",categories:["dynamic"],tags:["ball","falling-body","rolling","payload"],physics:physics({shape:"circle",radius:16,massKg:1.8,density:.0018,friction:.15,restitution:.35,impactReaction:"roll"}),appearance:{renderer:"payload-ball",color:"#c73b2e"},defaultState:"idle",animations:canvas("payload-ball"),rotatable:false,removable:false},
  fishBowl:{type:"fishBowl",displayName:"Goldfischglas",icon:"◯",description:"Statisches Glas; zerbricht bei ausreichend starkem Aufprall von oben.",categories:["fixed","container","trigger"],tags:["breakable","fish-container","solid-shape"],physics:{...fixed,shape:"circle",radius:55,massKg:5,restitution:.05,impactThreshold:4.5,waterReaction:"collect",impactReaction:"break"},appearance:{renderer:"sprite"},defaultState:"intact",animations:{intact:{kind:"sprite",asset:"/assets/mr-blue-animation-sprites.png",row:0,frames:3,columns:3,frameDurationMs:460,width:150,height:150,anchorY:-4,loop:true},breaking:{kind:"sprite",asset:"/assets/mr-blue-animation-sprites.png",row:1,frames:3,columns:3,frameDurationMs:180,width:150,height:150,anchorY:-4,loop:false},broken:{kind:"canvas",renderer:"broken-glass",loop:true}},rotatable:false,removable:false},
  fish:{type:"fish",displayName:"Mr. Blue",icon:"●",description:"Wird nach Glasbruch dynamisch und zappelt auf dem Boden.",categories:["dynamic","animal"],tags:["fish","cat-attractor","falling-body","water-animal"],physics:physics({shape:"circle",radius:20,massKg:.12,density:.001,friction:.7,staticFriction:.8,restitution:.12,inertiaLocked:true,waterReaction:"float",impactReaction:"bounce"}),appearance:{renderer:"sprite"},defaultState:"hidden",animations:{hidden:{kind:"canvas",renderer:"hidden",loop:true},flopping:{kind:"sprite",asset:"/assets/mr-blue-animation-sprites.png",row:2,frames:3,columns:3,frameDurationMs:150,width:86,height:86,anchorY:2,loop:true}},rotatable:false,removable:false},
  scissor:{type:"scissor",displayName:"Schere",icon:"✂",description:"Schließt durch Aufprall oder Zugspannung an einem Griff und schneidet ihr Ballonseil.",categories:["fixed","trigger"],tags:["impact-closable","rope-pullable","sharp","solid-shape"],physics:{...fixed,shape:"rectangle",width:70,height:56,massKg:1.2,impactThreshold:2.4,impactReaction:"close"},appearance:{renderer:"scissor",color:"#65777d"},defaultState:"open",animations:{open:{kind:"canvas",renderer:"scissor-open",loop:true},closing:{kind:"canvas",renderer:"scissor-closing",frames:4,frameDurationMs:65,loop:false},closed:{kind:"canvas",renderer:"scissor-closed",loop:true}},rotatable:false,removable:false},
  water:{type:"water",displayName:"Wasser",icon:"●",description:"Kollidierende Partikel, die fließen, sammeln und Feuer löschen.",categories:["dynamic","fluid"],tags:["water","falling-body"],physics:physics({shape:"circle",radius:5,massKg:.01,density:.0002,friction:.02,staticFriction:.02,airFriction:.002,restitution:.02,maxSpeed:11,waterReaction:"collect",fireReaction:"extinguish-source",impactReaction:"bounce"}),appearance:{renderer:"sprite"},defaultState:"flowing",animations:{flowing:{kind:"sprite",asset:"/assets/water-animation-sprites.png",row:0,frames:6,columns:6,frameDurationMs:120,width:24,height:20,loop:true},splashing:{kind:"sprite",asset:"/assets/water-animation-sprites.png",row:1,frames:6,columns:6,frameDurationMs:70,width:34,height:24,loop:false}},rotatable:false,removable:false},
  cannonball:{type:"cannonball",displayName:"Kanonenkugel",icon:"●",description:"Kleiner und leichter als eine Bowlingkugel; erhält ihren Impuls von der Kanone.",categories:["dynamic"],tags:["ball","projectile","falling-body","rolling"],physics:physics({shape:"circle",radius:11,massKg:2.5,density:.0025,friction:.12,restitution:.3,impactReaction:"roll"}),appearance:{renderer:"cannonball",color:"#333f43"},defaultState:"flying",animations:{flying:{kind:"canvas",renderer:"cannonball",loop:true}},rotatable:false,removable:false},
  rocket:{type:"rocket",displayName:"Rakete",icon:"▲",description:"Fest montierte Rakete. Berührt Feuer ihre Düse, zündet sie und startet nach einer kurzen Zündphase.",categories:["fixed","trigger","force-source"],tags:["rocket","fire-trigger","solid-shape"],physics:physics({shape:"sensor",width:66,height:150,massKg:8,density:.004,gravityScale:0,isStatic:true,isSensor:true,waterReaction:"collide",fireReaction:"ignite",impactReaction:"trigger"}),appearance:{renderer:"sprite"},defaultState:"mounted",animations:{mounted:{kind:"sprite",asset:"/assets/rocket-launch-sprites.png",row:0,frames:1,columns:4,frameDurationMs:500,width:104,height:104,loop:true},burning:{kind:"sprite",asset:"/assets/rocket-launch-sprites.png",row:0,frames:4,columns:4,frameDurationMs:130,width:104,height:104,loop:false},launching:{kind:"sprite",asset:"/assets/rocket-launch-sprites.png",row:1,frames:4,columns:4,frameDurationMs:180,width:132,height:132,loop:false},launched:{kind:"canvas",renderer:"rocket-smoke",frames:6,frameDurationMs:120,loop:false}},rotatable:false,removable:false},
};

export const getGadgetDefinition=(type:GadgetType)=>GADGET_CATALOG[type];
export const gadgetsWithTag=(tag:string)=>Object.values(GADGET_CATALOG).filter(gadget=>gadget.tags.includes(tag));
